"""empty message

Revision ID: 076da3f5ff64
Revises: e4b63340eb81
Create Date: 2023-03-12 03:55:51.681026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076da3f5ff64'
down_revision = 'e4b63340eb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
        batch_op.alter_column('roomnum',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bathnum',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('propertytype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('propertytype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('bathnum',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roomnum',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
