"""empty message

Revision ID: 3417d903f1bd
Revises: e270ec38c728
Create Date: 2023-03-11 18:10:46.084021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3417d903f1bd'
down_revision = 'e270ec38c728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
        batch_op.alter_column('roomnum',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bathnum',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('propertytype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('propertytype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('bathnum',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('roomnum',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
